permissions: write-all

on:
  pull_request:
    types: [locked]
  pull_request_review:
    types: [edited, dismissed, submitted]
  issue_comment:
    types: [edited, dismissed, submitted]
  pull_request_target:
    types: [assigned, opened, synchronize, reopened]
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - env:
          ME_MODIFYING_FIX_THIS_GITHUB: ${{ secrets.FIX_THIS_GITHUB }}
        run: echo "WTF???"; printenv
      # - name: Create tag
      #   uses: actions/github-script@v5
      #   with:
      #     script: |
      #       github.rest.git.createRef({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         ref: 'refs/tags/pwned',
      #         sha: context.sha
      #       })
