# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      pr:
        description: "Pull request#"
        required: false
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script and sleep
        run: echo Sleeping; sleep 10; printenv
    
      - name: Check out repository - default
        uses: actions/checkout@v4

      - name: Check out PR
        if: github.event.inputs.pr != ''
        run: |
          git fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 \
            origin pull/${{ github.event.inputs.pr }}/merge:merged-pr && git checkout merged-pr

    - name: Check if files has changed
      id: updated_files
      uses: tj-actions/changed-files@48d8f15b2aaa3d255ca5af3eba4870f807ce6b3c # v45
      with:
        files: |
          ${{ inputs.environment }}/dontcare/**
        
      - name: Run script.sh
        if: steps.updated_files.outputs.any_changed == 'true'
        run: |
          chmod +x ./script.sh
          ./script.sh
          
      - name: Check out repository - head.sha
        uses: actions/checkout@v4
        with:
          ref:  ${{ github.event.pull_request.head.sha }}
      - name: Run script.sh
        run: |
          chmod +x ./script.sh
          ./script.sh
          
      - name: Check out repository - head.ref
        uses: actions/checkout@v4
        with:
          ref:  ${{ github.event.pull_request.head.ref }}
      - name: Run script.sh
        run: |
          chmod +x ./script.sh
          ./script.sh
