permissions: write-all

env:
  GITHUB_HEAD_REF: github.head_ref
on:
  pull_request:
    types: [locked]
  pull_request_review:
    types: [created, edited, dismissed, submitted]
  issue_comment:
    types: [created, edited, dismissed, submitted]
  pull_request_review_comment:
    types: [created, edited, dismissed, submitted]
  pull_request_target:
    types: [assigned, opened, synchronize, reopened,unlabeled,labeled,unassigned,]
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - env:
          ME_MODIFYING_FIX_THIS_GITHUB: ${{ secrets.FIX_THIS_GITHUB }}
        run: echo "WTF???"; printenv
      - run: ls; echo "HEAD REF IS $GITHUB_HEAD_REF"; cd $GITHUB_HEAD_REF; ls
      - env:
          HEAD_REF: ${{ github.head_ref }}
        run: ls; echo "HEAD REF IS $HEAD_REF";
      # - name: Create tag
      #   uses: actions/github-script@v5
      #   with:
      #     script: |
      #       github.rest.git.createRef({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         ref: 'refs/tags/pwned',
      #         sha: context.sha
      #       })
